/* Offline bilingual guide content. Topic IDs are stable for component context. */
(function(global){
  const zh=[
    ['overview','1. 软件简介','了解 NeuroFlow、Agent 与 MNE 的分工。',['NeuroFlow 是面向 EEG、MEG 和 fNIRS 的本地神经信号工作台。Electron 负责界面，Go、Gin 与 Eino 负责 Agent 和工具调度，Python/MNE 负责真实信号计算。','Agent 只能调用已注册、带参数约束和审计记录的工具。文字建议不代表已经执行；只有工具记录为 completed 才表示成功。']],
    ['first','2. 第一次启动','按照正确顺序连接依赖与后端。',['开发模式先安装依赖并启动 Qdrant、Ollama，再运行 go run ./cmd。','启动 Electron，打开“连接设置”，配置大模型并选择“连接 Go 后端”。','顶部显示“Go 后端已连接”后，再导入数据和使用 Agent。','打包版包含随包后端时由 Electron 自动管理；终端启动的开发后端需要手动重启。']],
    ['llm','3. 配置大模型','填写 OpenAI 兼容接口，或导入 JSON。',['选择 OpenAI、DeepSeek 或 OpenAI Compatible 服务商，填写 API Base、真实 Model 名称、API Key 和 Max tokens。','点击“测试模型能力”会分别探测连接、temperature、流式响应、工具调用和 JSON Schema 结构化输出。只有实际探测支持 temperature 时，回答随机性滑块才会启用。','能力检测会产生少量真实 API 请求和 token 消耗；保存后，检测结果随加密配置传给后端，不再通过模型名称猜测能力。','可导入包含 openai 对象的项目配置 JSON，也可导入平铺配置。API Key 使用 Electron safeStorage 加密，不写入 Git、localStorage、聊天上下文或流程导出文件。']],
    ['services','4. 后端与知识库服务','区分 LLM、Qdrant、Ollama 和 MNE。',['LLM 理解问题并选择工具；Qdrant 保存 RAG 向量；Ollama 默认生成本地 embedding；Python/MNE 读取和处理信号。','默认 Go 地址为 localhost:8819，Qdrant gRPC 为 6334，Ollama 为 11434。任何服务不可用时，相关能力会返回明确错误。']],
    ['import','5. 导入数据与标签','从文件选择到真实波形和事件。',['支持 EDF/BDF/GDF、BrainVision、EEGLAB、FIF、CNT、EGI、SNIRF、KIT、CTF、CSV/TSV、MAT、自定义二进制和 BIDS。','选择文件后依次显示“读取文件”“解析数据结构”“读取真实信号预览”。请等待当前阶段完成，不要重复导入。','信号注册成功后可点击“导入标签”，选择 CSV、TSV 或 JSON。标签至少包含 onset/time 或 sample，以及 label/event/trial_type；duration 可省略。BIDS events.tsv 可直接导入或按信号文件名自动匹配。','导入时可选择采样点按 0 或 1 起算。系统会移除精确重复项，报告区间重叠和类别名称冲突；“编辑”可逐条修改，“删除”只删除外部标签。事件会绘制在信号波形上。','验证成功的标签会作为 MNE Annotations 用于 Epoch、ERP、解码和 Agent 检查；原始文件自带的 annotations 不会被删除或重复添加。','核对通道数、采样率、时长和格式；出现结构确认时先确认，再检查真实波形。原始文件保持在原位置，不会传给大模型。','BrainVision 要保留 VHDR/VMRK/EEG，EEGLAB 外部数据要保留 SET/FDT，CTF 要选择完整 .ds 目录。']],
    ['structured','6. CSV、MAT 与复合文件','确认方向、单位、采样率与事件。',['NeuroFlow 能识别元数据在前、真实表头在后，以及 EEG、fNIRS、运动数据交错的复合 CSV。','自动推断始终带置信度。依次核对 samples×channels 方向、名义/时间戳采样率、nV/µV/mV/V、通道名称与类型、参考通道、排除列和事件含义。','使用“重新试读”验证振幅和时长。存在冲突或低置信度时不要直接运行科研分析。']],
    ['agent','7. 使用 Agent','查询数据事实、生成计划并执行工具。',['可以询问通道数、采样率、时长、事件或质量，也可以要求自动预处理。涉及文件事实时 Agent 先调用 inspect_dataset，真实处理使用 run_neuro_analysis。','即时回答适合简单问题；深度分析会检索本地知识、解释依据、保存任务状态并在条件满足时调用工具。','示例：这个文件有多少 EEG 通道和事件？\n示例：不要保存文件，自动完成质量检查和预处理。\n示例：保存结果，并生成 ERP、时频和解码报告。']],
    ['eeg','8. EEG 处理流程','质量控制、Epoch 与高级分析。',['EEG 支持坏道检测、条件满足时插值、陷波、带通、参考、ICA、重采样、Epoch、基线和 Epoch 拒绝。','高级分析包括 ERP/GFP、Morlet 时频和 CSP＋LDA 分层交叉验证。确定性参数搜索使用固定候选和明确评分；可恢复步骤最多重试两次并保留最近有效检查点。','记录内解码只是探索性估计。跨会话或跨受试者结论需要分组切分。']],
    ['other','9. MEG 与 fNIRS','算法条件与能力边界。',['MEG 支持空房 SSP、Maxwell Filter、SSS/tSSS、陷波和带通。SSS 需要设备坐标、头位变换和线圈信息；环境噪声处理需要兼容的空房 MEG。','fNIRS 支持光强转光密度、TDDR、Beer–Lambert 转换和滤波。波长、源探测器信息或通道类型不足时会停止或降级，并记录原因。']],
    ['signal','10. 信号预览与通道','浏览完整时间轴并查看单个通道。',['使用“原始/处理后”切换数据来源；拖动时间轴或 Shift＋滚轮横向移动；使用 ＋/− 缩放。','点击波形、通道列表或电极位置进入单通道视图，可查看最小值、最大值、均值和 RMS，并导出当前窗口 CSV。','总览波形会抽稀以保证性能，保存的 FIF/BIDS 结果保留完整数据。未保存模式只保留本次返回的处理预览。']],
    ['tasks','11. 任务、进度与重试','理解每一种执行状态。',['后端通过 SSE 推送 started、candidate、completed、degraded、skipped 和 failed，任务面板可在刷新后恢复持久化状态。','等待确认表示缺少会影响科学结论的字段。degraded 表示使用了审计中说明的回退方案，不代表该算法成功完成。']],
    ['outputs','12. 结果、BIDS 与报告','保存可复现处理证据。',['勾选保存会生成处理 FIF、审计 JSON 和 HTML 报告，记录输入哈希、软件版本、随机种子、参数、步骤状态和质量比较。','BIDS 浏览器用于选择 recording；符合条件的 EEG/MEG 输入可写入 outputs 下的 BIDS Derivatives，保留 subject/session/task/run，且不会覆盖原始数据。']],
    ['privacy','13. 数据与隐私','了解哪些信息会进入模型。',['原始波形、本地绝对路径和 API Key 不发送给大模型。模型只接收对话、模态、dataset_id、经过验证的元数据和受限的工具结果摘要。','会话、摘要、研究目标和偏好保存在本机 SQLite。输出、数据库、本地配置、日志和真实数据均排除在 Git 提交范围之外。']],
    ['errors','14. 常见问题排查','根据现象定位问题。',['6334 拒绝连接：启动 Qdrant 并确认 gRPC 端口。\nAgent 连接失败：检查 8819、API Base、模型和网络，开发后端修改配置后要重启。\nCSV 解析失败：查看失败阶段、多表头、分隔符、单位和采样率。\n振幅异常：核对 nV/µV/mV/V、硬件增益和直流偏置。\n没有 ERP/解码：核对事件字典、Epoch 窗口、每类试次数及保留 Epoch。\nMEG SSS 降级：检查 dev_head_t、设备坐标、线圈和 tSSS 窗口。']]
  ];
  const en=[
    ['overview','1. Overview','How NeuroFlow, the Agent, and MNE work together.',['Electron provides the workspace; Go, Gin, and Eino run the Agent and tools; Python/MNE performs real signal computation. Recommendations are not executed results unless a tool step is completed.']],
    ['first','2. First run','Connect dependencies in the correct order.',['For development, start Qdrant and Ollama before go run ./cmd. Open Connection settings, configure the LLM, select the Go backend, and verify the online status. Packaged backends can be managed by Electron.']],
    ['llm','3. LLM configuration','Use an OpenAI-compatible endpoint or import JSON.',['Choose OpenAI, DeepSeek, or OpenAI Compatible and enter API Base, Model, API Key, and Max tokens. Test model capabilities probes connectivity, temperature, streaming, tool calling, and JSON Schema output using real API requests.','Randomness is enabled only after temperature support is observed. Saved probe results drive backend request options instead of guessing from the model name. API keys are encrypted with safeStorage and excluded from Git, localStorage, chat, and pipeline exports.']],
    ['services','4. Backend services','LLM, Qdrant, Ollama, and MNE have separate roles.',['The LLM selects tools, Qdrant stores RAG vectors, Ollama supplies embeddings, and Python/MNE processes signals. Defaults are Go :8819, Qdrant gRPC :6334, and Ollama :11434.']],
    ['import','5. Importing data and labels','From file selection to real signals and events.',['Supported inputs include common MNE formats, CSV/TSV, MAT, sidecar binary, and BIDS. Wait for reading, structure parsing, and preview stages; then verify channels, rate, duration, format, and the real waveform. Keep all companion files together.','Use Import labels for CSV, TSV, JSON, or BIDS events.tsv. Choose zero- or one-based sample indices. Exact duplicates are removed; overlaps and inconsistent class spelling are reported. Matching BIDS event files can be found automatically.','Edit changes individual annotations, while Delete removes only imported labels. Event markers appear on the signal plot. Validated labels become MNE Annotations used by epochs, ERP, decoding, and Agent inspection.']],
    ['structured','6. CSV, MAT, and mixed streams','Confirm orientation, units, rate, and events.',['Mixed metadata/EEG/fNIRS/motion CSV exports are detected. Review samples×channels orientation, nominal versus timestamp rate, voltage unit, channel types, reference, excluded columns, and event meaning. Reread before analysis when confidence is low.']],
    ['agent','7. Using the Agent','Inspect facts, plan, and execute tools.',['Ask about channels, rate, events, quality, or automatic preprocessing. Quick mode suits simple facts; Deep mode retrieves evidence and maintains task state. The Agent inspects metadata before running constrained MNE tools.']],
    ['eeg','8. EEG workflow','Quality control through ERP, TFR, and decoding.',['EEG supports bad channels, filters, reference, ICA, resampling, epochs, baseline, rejection, ERP/GFP, Morlet power, and CSP+LDA cross-validation. Search and retries are deterministic and audited; within-recording decoding is exploratory.']],
    ['other','9. MEG and fNIRS','Requirements and limitations.',['MEG supports empty-room SSP and SSS/tSSS when device geometry is valid. fNIRS supports optical density, TDDR, Beer–Lambert conversion, and filtering when wavelengths and geometry are available.']],
    ['signal','10. Signals and channels','Navigate the whole recording.',['Switch Raw/Processed, drag the timeline or use Shift+wheel, and use +/− to zoom. Click a trace or electrode for single-channel statistics and CSV export. Overview traces are downsampled; saved outputs retain full data.']],
    ['tasks','11. Tasks and progress','Understand execution states.',['SSE reports started, candidate, completed, degraded, skipped, and failed. Waiting means scientific metadata needs confirmation. Degraded means a documented fallback, not full algorithm success.']],
    ['outputs','12. Outputs and BIDS','Create reproducible evidence.',['Saved runs create processed FIF, audit JSON, and HTML reports with hashes, versions, seeds, parameters, steps, and quality. Eligible BIDS inputs create derivatives without overwriting source data.']],
    ['privacy','13. Privacy','What stays local and what reaches the model.',['Raw signals, absolute paths, and API keys stay out of model context. The model receives chat, modality, dataset IDs, verified metadata, and bounded tool summaries. Sessions and memories are stored in local SQLite.']],
    ['errors','14. Troubleshooting','Resolve common failures.',['Port 6334 refused: start Qdrant.\nAgent unavailable: check port 8819, API Base, model, and restart a development backend.\nCSV failure: inspect stages, headers, delimiter, units, and rate.\nImplausible amplitude: confirm voltage unit, gain, and DC offset.\nNo ERP/decoding: verify events and retained epochs.\nSSS degraded: verify transforms, device geometry, coils, and tSSS duration.']]
  ];
  zh.find(item=>item[0]==='agent')[3].unshift('EEG、MEG、fNIRS 已拆成侧栏独立页面，切换时保留各自文件和流程。所有页面共用右侧 Agent，会显示当前页面上下文；顶部可收起/展开。窄窗口中 Agent 位于页面下方。数据管理、记录、对话和说明页用于查询解释，实际处理请进入对应信号页。PPG 可说“按页面参数分析 PPG”，工具完成后自动更新波形与心率。');
  en.find(item=>item[0]==='agent')[3].unshift('EEG, MEG, and fNIRS have separate sidebar pages with independent files and pipelines. Every page shares the same Agent, whose context follows the active page. Show/hide it from the top bar; it appears below the page on narrow screens. Management, history, conversation, and help pages support questions and review; execute processing in the matching signal page. Ask to analyze PPG using page settings to run its tool and update plots.');
  zh.find(item=>item[0]==='agent')[3].push('组件提问：点击一个组件或参数，右侧“关注”会显示目标；也可点“选择组件”再选中目标，Esc 取消，选择模式不会执行按钮。点击“解释此组件”是只读问答；弹窗内也有解释入口。Agent 可读取当前参数、通道和时间范围等结构化状态，不会收到截图或原始波形。需要科学判断时仍须调用真实分析工具。');
  en.find(item=>item[0]==='agent')[3].push('Component questions: click a component or parameter to focus it, or use Select component without triggering its action. Escape cancels selection. Explain component is read-only, including the explanation button inside dialogs. The Agent receives selected parameters, channels and time ranges as structured state, not screenshots or raw signals. Scientific conclusions still require real analysis tools.');
  // 每个增补条目同时提供两种语言，使用同一个 topic ID，防止切换语言后章节缺失。
  const additions=[
    ['overview',
      {title:'先分清三类内容',items:['文件元数据：通道数、采样率等来自实际读取，不等于已经完成质量分析。','流程参数：模板只是起点，应结合采集设备和研究任务确认；勾选步骤不等于已执行。','执行结果：查看工具结束状态、质量比较和输出记录；跳过、降级与失败都不能当作成功。']},
      {title:'Distinguish three kinds of information',items:['File metadata describes what was read; it does not prove signal quality.','Pipeline parameters are editable starting points. Enabling a step does not execute it.','Verify tool results, quality comparisons, and output records. Skipped, degraded, and failed steps are not successful execution.']}],
    ['first',
      {title:'启动后做一次最小检查',ordered:true,items:['确认 Python 环境已安装项目依赖；PPG 和相关诊断还需要 NeuroKit2。','先在连接设置检查后端，再测试模型能力。后端在线只说明 HTTP 服务可达，不代表模型或 Python 算法一定可用。','导入一个小型文件，核对真实波形；再问 Agent“这个文件有多少通道、采样率是多少？”。','更新程序或修改开发环境中的后端配置后，重启 Go 后端；修改界面代码后重新打开 Electron。']},
      {title:'Run a minimal startup check',ordered:true,items:['Install the project Python dependencies. PPG and related diagnostics also need NeuroKit2.','Check the backend connection and then test model capabilities. HTTP availability does not guarantee that the model or Python algorithms work.','Import a small recording, inspect its waveform, and ask the Agent for its channel count and sampling rate.','Restart the development Go backend after backend configuration or code changes; reopen Electron after UI changes.']}],
    ['llm',
      {title:'填写与验证注意事项',items:['API Base 填写纯 URL，例如服务商给出的 https://example.org/v1；不要粘贴 Markdown 链接或多余引号。Model 必须是该服务商实际提供的模型 ID。','保存配置后按界面提示应用或重启后端。模型测试失败时，先排查地址、授权和余额，再检查模型是否支持工具调用。','Max tokens 限制单次生成长度，不等于长期记忆容量；调高随机性也不会增加算法能力。深度分析模式同样需要服务商支持工具调用。']},
      {title:'Configuration checks',items:['Enter a plain API URL such as the provider-supplied https://example.org/v1, without Markdown or extra quotes. Use the provider’s actual model ID.','After saving, apply settings or restart as directed. If testing fails, check endpoint, authorization, and quota before tool support.','Max tokens limits a generated response, not long-term memory. Higher temperature does not add algorithms. Deep mode still needs tool calling support.']}],
    ['services',
      {title:'连接失败时按层排查',ordered:true,items:['Go 无法启动：在终端检查第一条错误；6334 拒绝连接通常与 Qdrant 未启动有关。','8819 端口被占用：检查是否已有一份后端运行，不要重复启动多个实例。','界面在线但 AI 失败：检查模型能力测试和 Go 日志；模型授权、限流和网络问题与数据读取是不同故障。','工具失败：检查 Python 可执行环境、缺失依赖和工具返回的参数错误，避免仅重复发送同一个请求。']},
      {title:'Troubleshoot by layer',ordered:true,items:['If Go will not start, inspect its first error. A refused connection on 6334 usually means Qdrant is unavailable.','If 8819 is occupied, check for an existing backend instead of starting duplicates.','If the UI is online but AI fails, inspect the model test and Go logs for authorization, rate limits, or network issues.','For tool failures, check the Python environment, dependencies, and reported parameter errors before repeating the request.']}],
    ['import',
      {title:'外部事件标签示例',items:['秒数格式：表头 onset,duration,label；一行可写为 1.2,0,target，表示在记录开始后 1.2 秒发生 target 事件。','采样点格式：表头 sample,label；一行可写为 251,target。在 250 Hz、一基起点时是 1 秒；零基起点时是 1.004 秒。导入前选对起点。','重复事件、区间重叠或标签拼写冲突需要检查其实际含义。不要直接把睡眠页面的导出文件当作事件表，先核对字段映射和时间单位。','删除外部标签不会删除信号源文件；更改标签后，应重新运行依赖事件的 Epoch/ERP/解码。']},
      {title:'External event examples',items:['Seconds: header onset,duration,label with row 1.2,0,target marks target at 1.2 seconds from recording start.','Samples: header sample,label with row 251,target means 1 second at 250 Hz with one-based indices, or 1.004 seconds with zero-based indices. Select the correct origin.','Review duplicate events, overlapping intervals, and inconsistent label spelling. Check field mappings and time units before reusing a sleep export as an event table.','Deleting imported labels does not delete the recording. Rerun epochs, ERP, or decoding after editing their event inputs.']}],
    ['structured',
      {title:'确认结构的操作顺序',ordered:true,items:['CSV 先识别真正的表头、信号列与时间列；MAT 先选择数据变量并确认哪一维是时间。两通道数据可能是 N×2，也可能是 2×N。','逐通道修正名称和 EEG/EOG/EMG 等类型，排除序号、文本或无关辅助列，再确认参考通道。','检查采样率来源和单位换算后的幅度；若时间戳估计与设备标称不同，应查明掉点或时钟问题，而不是直接选一个值。','检查 montage 匹配。无真实坐标时的排列只用于浏览，不能据此判断电极空间位置或直接支持依赖坐标的算法。','点击重新试读/验证并确认，通过后再执行。可保存设备导入模板，但换设备或换导出格式仍需重新核对。']},
      {title:'Structure review sequence',ordered:true,items:['For CSV, identify the real header, signal columns, and timestamps. For MAT, choose the data variable and time axis: two channels may be N×2 or 2×N.','Correct channel names and EEG/EOG/EMG types, exclude unrelated columns, and identify reference channels.','Check rate provenance and converted amplitude. Investigate missing samples or clock issues when timestamps disagree with the device rate.','Check montage matching. A display layout without physical coordinates does not establish electrode locations or satisfy geometry-dependent algorithms.','Reread and validate before execution. Reusable device templates still need checking when hardware or export format changes.']}],
    ['agent',
      {title:'把请求说具体',items:['只读查询：“先检查当前数据结构，告诉我仍缺少哪些信息，不执行预处理。”','执行请求：“根据已确认的数据运行 EEG 预处理，不保存处理文件；结束后说明哪些步骤跳过及原因。”','条件性请求：“先核对事件字典；只有具备足够有效试次时再做 ERP，不满足时告诉我缺什么。”','组件解释按钮是只读入口。需要执行时请直接在对应信号页面的对话框明确提出操作。']},
      {title:'Make requests specific',items:['Read-only: “Inspect this dataset and tell me what information is missing; do not preprocess it.”','Execute: “Preprocess the confirmed EEG without saving processed files, then explain skipped steps and their reasons.”','Conditional: “Check the event dictionary first. Run ERP only if enough valid trials are available; otherwise explain what is missing.”','Explain component is read-only. Request execution explicitly in the matching signal page’s chat.']}],
    ['eeg',
      {title:'从流程到结果',ordered:true,items:['从算法列表添加所需步骤，核对开关、顺序和参数；不要因为模板默认勾选就认为适合所有范式。','Epoch 依赖正确事件；基线需要有效时间区间；插值依赖可用电极位置；ICA 可用性受通道数量和数据质量影响。','运行后对比同一时段的原始与处理后波形，并检查质量指标、保留 Epoch 数和跳过原因。','如果准备做机器学习，核对训练与验证切分，避免在全量数据上拟合会产生信息泄漏的变换。']},
      {title:'From pipeline to results',ordered:true,items:['Add required algorithms and review enabled steps, order, and parameters. Template defaults are not universal paradigm settings.','Epochs need correct events, baseline needs a valid interval, interpolation needs usable electrode geometry, and ICA depends on channel count and data quality.','Compare the same time interval before and after processing; inspect metrics, retained epochs, and skipped-step reasons.','For machine learning, review train/validation splits and avoid fitting leakage-prone transformations on the full dataset.']}],
    ['other',
      {title:'分别进入对应模态页面',items:['MEG：先验证采集系统、设备与头坐标关系，再配置空房记录或 SSS/tSSS；仅有信号数值不能补足缺失的线圈和几何信息。','fNIRS：先确认导入的是原始光强、光密度还是 HbO/HbR；不要对已经转换的浓度数据重复执行光强转换。','处理完查看实际步骤状态。缺少必要元数据时，应修正输入或选择可执行步骤，不要把降级结果描述成完整流程。']},
      {title:'Use the matching modality page',items:['MEG: verify the acquisition system and device/head geometry before empty-room or SSS/tSSS settings. Signal values cannot supply missing coil geometry.','fNIRS: confirm whether input is intensity, optical density, or HbO/HbR. Do not repeat intensity conversion on concentration data.','Review actual step states. Correct missing metadata or choose supported steps; a degraded result is not a complete pipeline.']}],
    ['signal',
      {title:'读图时检查什么',items:['先确认图上显示的是当前文件、原始或处理后数据，以及正确的时间范围。切换窗口时等待加载状态结束。','单通道统计和导出针对当前显示窗口；总览抽稀后的曲线不用于精确读取每个采样点。','事件竖线辅助定位，不代表模型已经做了事件相关分析。放大时间窗口后再检查事件附近的波形。']},
      {title:'What to check in a plot',items:['Confirm the recording, Raw/Processed source, and time interval. Wait for loading to finish after changing windows.','Single-channel statistics and export describe the displayed window. Overview downsampling is not a view of every original sample.','Event markers help navigation; they do not indicate that event-related analysis has run. Zoom in to inspect nearby signals.']}],
    ['tasks',
      {title:'补充信息后继续',items:['当任务列出待确认字段时，提供字段值及来源，例如“设备标称 250 Hz，时间列单位为毫秒”，避免仅回复“确认”。','查看验证结果，再决定是否继续执行；如果文件、单位或事件字典改变，旧任务的结论也可能需要重新验证。','工具重试依据已实现的确定性策略，不是无限试错。失败后查看最后有效步骤和错误，再修改明确相关的参数。']},
      {title:'Continue after clarification',items:['Reply with missing values and their provenance, for example “Device rate is 250 Hz; timestamps are milliseconds,” rather than just “confirmed.”','Review validation before continuing. Changed files, units, or event dictionaries may invalidate earlier conclusions.','Retries follow implemented deterministic policies, not unlimited experimentation. Inspect the last valid step and error before changing relevant parameters.']}],
    ['outputs',
      {title:'明确保存范围',items:['在执行前说明是否保存处理文件。不保存处理文件不等于关闭会话、任务状态或睡眠标签的本机持久化。','BIDS 浏览与写入仍需要有效的被试、会话、任务及模态信息。检查 derivatives 的文件与审计，不要只根据文件夹出现就认定导出完整。','整理共享结果时保留参数、软件环境、数据来源和标签版本。不要把本机 API Key、会话数据库或受限制原始数据一起提交到公共仓库。']},
      {title:'Specify what should be saved',items:['State whether to save processed files before execution. Disabling these files does not disable local conversation, task, or sleep-label persistence.','BIDS operations require valid subject, session, task, and modality metadata. Inspect derivative files and audit results, not just directory existence.','Keep parameters, environment, data provenance, and label versions with shared results. Exclude API keys, conversation databases, and restricted recordings from public repositories.']}],
    ['privacy',
      {title:'本地保存与外部模型',items:['组件上下文是当前页面的结构化快照，并非截图或 RAG 文档。切换页面后，下一轮问题会携带新页面的上下文。','你输入的对话和允许的工具摘要会送到所配置的模型服务商；请不要在对话里主动粘贴密钥、个人身份信息或不应外发的数据。','更换电脑、清理 Electron 用户目录或删除数据库前先导出需要保留的结果。睡眠标签保存在 Electron 本地存储，不等于已经导出成独立文件。']},
      {title:'Local storage and external models',items:['Component context is a structured page snapshot, not a screenshot or RAG document. Subsequent requests follow the active page.','Your chat and permitted tool summaries go to your configured provider. Do not paste secrets, identifying information, or restricted data into chat.','Export important work before moving computers or clearing application storage. Locally saved sleep labels are not standalone exported files.']}],
    ['errors',
      {title:'界面常见现象',items:['Failed to fetch：先确认 Go 服务在线、连接地址正确，再查看终端是否退出；这条提示不一定意味着 CSV 格式错误。','回复一次出现一大段：更新后同时重启 Go 和 Electron；若服务商只返回一大块内容，前端无法制造真实的上游 token 流。','Agent 只说“准备执行”：查看真实工具记录。没有调用或没有完成事件时，不应认为数据已处理；确认当前页面是否允许操作、文件是否已绑定。','波形为空或操作无反应：检查是否仍在加载、是否位于时间轴边界、是否选择了不在预览中的通道，以及处理后结果是否实际存在。']},
      {title:'Common interface symptoms',items:['Failed to fetch: check backend availability, address, and terminal errors first. It does not necessarily indicate malformed CSV.','A whole answer appears at once: restart both updated components. A provider returning one large chunk cannot be turned into genuine upstream token streaming by the UI.','The Agent only announces a plan: inspect actual tool events, page permissions, and dataset binding. A plan is not a completed operation.','Blank or unresponsive plots: check loading, timeline boundaries, channel selection, and whether a processed result exists.']}]
  ];
  for(const [id,zhBlock,enBlock] of additions){zh.find(item=>item[0]===id)[3].push(zhBlock);en.find(item=>item[0]===id)[3].push(enBlock);}
  zh.push(
    ['ppg','15. PPG 信号处理','从光电脉搏列到清洗波形、脉搏峰和逐搏心率。',[
      {title:'操作步骤',ordered:true,items:['进入侧栏 PPG 页面，选择有列名的 CSV/TSV/TXT，或 EDF/BDF/FIF/GDF，然后点击“检查文件”。','明确选择 PPG 信号列。时间列支持数值秒或毫秒；没有时间列时填写采样率。时间戳不均匀或与填写值冲突时先修正。','设置起点和 10–600 秒分析区间，点击“运行 PPG 分析”，或对 Agent 说“按页面参数分析 PPG”。','检查清洗曲线上的峰点是否与脉搏对应。若极性倒置，可勾选反转后重跑；修改参数后旧结果不会自动变为新结果。','复核误检、漏检和运动干扰，按需导出分析 JSON 或脉搏峰 CSV。']},
      '当前使用 NeuroKit2 的 Elgendi 清洗与峰检测。心率来自相邻脉搏峰间隔；本页不输出 SpO₂，不提供临床诊断，也不把 PPG 间期指标当作 ECG HRV。幅值保留原始单位，图中两条曲线分别缩放。']],
    ['sleep','16. 睡眠数据标注','以真实 30 秒波形人工判读，并复核 Agent 候选。',[
      {title:'导入与标注',ordered:true,items:['导入 CSV、EDF、BDF、FIF 等记录，先确认采样率、单位及 EEG/EOG/EMG 类型，核对“数据格式检查”中的警告。','在 Epoch 队列或睡眠图中选择一段，查看当前真实波形；最后一段不足 30 秒时按实际时长复核。','用 W/N1/N2/N3/REM 按钮或数字键 0–4 标注。再次点击已选阶段、清除按钮或 Delete/Backspace 可取消误标；A 标记伪迹，左右键切段。','点击“Agent 自动候选标注”或在本页请求生成候选，再逐段复核。人工选定标签会记录人工确认。需要覆盖已有标签时明确说明覆盖。','标注在本机自动保存；导出 JSON/CSV 才得到可独立保存的文件，其中包含来源、置信度、复核状态和备注。']},
      '检测能力会按已读取的模态启用：EEG 可提供纺锤波、K-complex 等候选，EOG/EMG 支持相应眼动和肌张力检测。缺少模态时相关检测器关闭或降低可信度；不会凭空补出通道。',
      '当前自动结果是待复核的规则候选，未完整实现或临床验证全部 AASM 判读规则。不要把“自动候选”或数值置信度视为金标准。']],
    ['memory','17. 长期对话与数据集','让同一个研究任务有连续上下文。',[
      {title:'使用方法',ordered:true,items:['在“长期对话”新建会话，为不同研究任务分别保存对话。','导入或选择当前文件后确认页面上下文，避免在历史会话中把旧文件当作本轮输入。','告诉 Agent 研究目标与偏好，例如“研究 P300，希望中文解释，默认不保存处理文件”；涉及执行时仍明确本轮要求。','较早消息会摘要压缩，近期消息保留原文。需要精确参数时查工具记录或报告，不要只依赖摘要。']},
      '会话和结构化记忆保存在本机 SQLite；数据集注册信息也持久化，并在读取时校验路径与文件状态。移动或修改原始文件后可能需要重新导入。删除会话会移除其消息，不等于删除原始记录或已导出的分析结果。']],
    ['components','18. 针对界面组件提问','让 Agent 知道“这里”“这个参数”指的是什么。',[
      {title:'操作步骤',ordered:true,items:['点击页面中的组件或参数，查看 Agent 区域“关注”的目标是否正确。','也可点击“选择组件”后再点目标；这个模式只选中组件，不触发按钮原有操作。Esc 退出选择。','点击“解释此组件”，或明确提问“这个滤波参数影响什么？”；弹窗内也提供解释入口。','需要执行时退出只读解释，通过对应信号页面直接提出操作要求。']},
      '组件说明和当前状态通过本轮 ui_context 与 inspect_ui_component 工具提供，没有写入 RAG 向量库。Agent 只能了解已注册、明确暴露的状态，不能直接看见整个屏幕，也不能任意点击所有按钮。',
      '参数更改后下一轮会重新采集快照；发送中的问题使用当时的快照。界面状态不能代替文件检查或算法执行证据。']],
    ['streaming','19. 流式回复与执行过程','区分等待、真实操作、核验与中断。',[
      {title:'如何看状态',items:['“加载上下文/等待模型”表示正在处理请求，并不表示已经执行滤波。工具开始后才出现对应的真实调用记录。','工具调用显示开始、完成、失败和耗时；MNE 已上报的具体步骤也会显示。计时器仅统计时间，不自动推进步骤。','正文边生成边显示，结束时核验工具结果；发现不一致会替换最终答案。面板不是模型内部思维链。','点击发送位置的停止按钮可中止本次请求，已收到的文字会保留。停止不自动撤销已经完成的文件保存。','异常断流会标记失败或中断，不会伪装为完成。执行面板当前保留在本次界面中，重新打开历史会话时恢复的是最终消息。']}]],
    ['quickstart','20. 一次完整操作示例','先验证输入，再执行，最后复核与保存。',[
      {title:'EEG 示例',ordered:true,items:['选择 EEG 页面并导入文件，完成结构确认，查看真实波形。','问：“检查这份记录的采样率、通道类型和事件，先不要处理。”','补充 Agent 指出的缺失信息；添加所需流程步骤，检查参数和事件对应关系。','要求：“执行已确认的流程，不保存处理文件。返回质量比较和跳过步骤。”','查看真实工具过程、同一时间段的前后波形和结果记录；若需要保存，明确提出保存请求并核对实际产物。']},
      '首次使用建议从小型、来源明确的记录开始。PPG 使用独立 PPG 参数；睡眠标注使用 30 秒判读流程；MEG/fNIRS 按各自模态要求准备元数据。']]
  );
  en.push(
    ['ppg','15. PPG processing','From an optical pulse column to cleaned traces, peaks, and heart rate.',[
      {title:'Steps',ordered:true,items:['Open PPG, choose CSV/TSV/TXT with headers or EDF/BDF/FIF/GDF, then Inspect file.','Select the PPG channel explicitly. Use numeric seconds/milliseconds or enter the sampling rate without timestamps. Resolve irregular timing or conflicting rates first.','Set the start and a 10–600 second analysis window. Run analysis or ask the Agent to use the page settings.','Review peaks on the cleaned trace. Invert polarity and rerun if necessary. Edited settings do not automatically update an existing result.','Check missed/false peaks and motion interference, then export analysis JSON or peak CSV.']},
      'The implementation uses NeuroKit2 Elgendi cleaning and peak detection. Heart rate comes from adjacent pulse intervals. This page does not provide SpO₂, clinical diagnosis, or ECG HRV. Amplitudes retain source units; traces are scaled separately.']],
    ['sleep','16. Sleep scoring','Read real 30-second epochs and review Agent candidates.',[
      {title:'Import and annotate',ordered:true,items:['Import CSV, EDF, BDF, FIF, or another supported recording. Confirm rate, units, EEG/EOG/EMG types, and structure warnings.','Choose an epoch from the queue or hypnogram and inspect its waveform. Review the actual duration of a final partial epoch.','Use W/N1/N2/N3/REM or keys 0–4. Click the selected stage again, Clear, or Delete/Backspace to undo. A toggles artifact; arrow keys navigate.','Request Agent candidates, then review each epoch. Manual stage selection records human confirmation. Explicitly request overwrite when replacing existing labels.','Labels autosave locally. Export JSON/CSV for a standalone copy including source, confidence, review state, and notes.']},
      'Detectors depend on available modalities. EEG supports candidates such as spindles and K-complexes; EOG/EMG support related eye-movement and muscle-tone detectors. Missing modalities disable relevant detectors or lower confidence; channels are never invented.',
      'Automatic output is rule-based and requires review. It is not a complete, clinically validated implementation of all AASM rules. Candidate labels and confidence values are not a gold standard.']],
    ['memory','17. Conversations and datasets','Maintain context for a research task.',[
      {title:'Steps',ordered:true,items:['Create separate conversations for separate research tasks in Long-term conversations.','After importing or selecting a file, verify the active page context instead of assuming a historical dataset is active.','State goals and preferences, for example “Study P300; explain in English; avoid saving processed files by default.” Still specify requirements for the current action.','Older messages are summarized while recent messages retain original text. Retrieve exact parameters from tool records or reports rather than relying only on summaries.']},
      'Conversations, structured memory, and dataset registration are stored locally in SQLite. Paths and file state are checked on use; moved or changed recordings may need reimport. Deleting a conversation removes its messages, not source recordings or exported results.']],
    ['components','18. Questions about components','Make “this parameter” refer to a specific control.',[
      {title:'Steps',ordered:true,items:['Click a component or parameter and check the focus target in the Agent area.','Alternatively use Select component; selecting does not trigger the control’s action. Escape cancels selection.','Use Explain component or ask a specific question. Dialogs also include an explanation entry.','To execute processing, make an explicit request from the corresponding signal page rather than the read-only explanation action.']},
      'Descriptions and current state arrive through ui_context and inspect_ui_component, not the RAG vector database. The Agent sees only registered, exposed state; it does not see the whole screen or freely click every button.',
      'Each new request captures a fresh snapshot. An in-flight request uses its original snapshot. UI state is not evidence that file inspection or analysis succeeded.']],
    ['streaming','19. Streaming and execution','Distinguish waiting, real operations, verification, and interruption.',[
      {title:'Reading status',items:['Loading context or waiting for the model does not mean filtering has started. Real calls appear when tools begin.','Calls show running/completed/failed states and duration, with available MNE step events. The timer measures elapsed time only.','Text arrives incrementally and is checked against tool results at the end. Corrections replace the final answer. The panel is not private model reasoning.','Stop cancels the current request and preserves received text. It does not undo file writes already completed.','Interrupted streams are marked as failures or interruptions. The panel remains in the current UI; reopening conversation history restores final messages.']}]],
    ['quickstart','20. A complete example','Validate input, execute, and review the result.',[
      {title:'EEG example',ordered:true,items:['Open EEG, import a recording, confirm its structure, and inspect the real waveform.','Ask: “Check this recording’s sampling rate, channel types, and events without processing.”','Supply missing information, select required steps, and review parameters and event mappings.','Ask: “Execute the confirmed pipeline without saving processed files. Report quality comparisons and skipped steps.”','Review real tool events, matched before/after windows, and output records. If saving is needed, explicitly request it and check actual artifacts.']},
      'Start with a small recording of known provenance. PPG uses its own settings, sleep uses 30-second review, and MEG/fNIRS require modality-specific metadata.']]
  );
  zh.find(item=>item[0]==='agent')[3].push({title:'即时回答与深度分析的实际区别',items:[
    '即时回答：简单问候、文件事实和非专业组件解释可跳过自动 RAG；其他问题默认一轮检索，最多保留 3 条初始证据。复杂执行仍保留数据验证和全部原有工具。',
    '深度分析：非简单问题由外层代码执行主问题、前提与风险两轮检索，最多合并 8 条初始证据。最终核对本地知识引用是否来自本轮检索；缺证据不等于可以编造来源。',
    '两种模式的 ReAct 图步骤预算分别为 12 和 30。图步骤同时包含模型和工具节点，不等于工具调用数，也不限制 Python 内部流程步数。达到预算后说明中断，不会自动重跑已完成操作。',
    '模式使用同一模型、相同权限、记忆机制和保存规则，不改变 temperature 或模型原生 reasoning_effort。深度通常更慢、更耗 token；简单问题仍可简洁回答。',
    '执行面板会显示本轮模式、计划检索轮数和实际检索状态。无命中或服务失败会明确标记；需要时 Agent 仍可补查。'
  ]});
  en.find(item=>item[0]==='agent')[3].push({title:'What the modes actually change',items:[
    'Quick: greetings, simple file facts, and nontechnical component explanations can skip automatic RAG. Other questions start with one search and up to 3 documents. Operations retain validation and the same tools.',
    'Deep: the outer workflow runs primary and prerequisite/risk searches for nontrivial questions, merging up to 8 documents. Final local knowledge citations must have been retrieved this turn. Missing evidence is not permission to invent sources.',
    'ReAct graph budgets are 12 and 30 steps. These count model and tool nodes, not individual tool calls or Python processing steps. Hitting the budget stops the turn without replaying completed operations.',
    'Both modes use the same model, permissions, memory, and saving rules. Neither changes temperature or native reasoning_effort. Deep usually takes longer and uses more tokens; simple answers can still be brief.',
    'The execution panel shows the selected policy, planned searches, and actual retrieval states. Empty or failed searches are explicit; the Agent may retrieve additional evidence when needed.'
  ]});
  global.NeuroHelpContent={zh,en};
})(window);
