// Package batchstate persists multi-recording analysis queues in SQLite.
package batchstate

import("context";"database/sql";"encoding/json";"errors";"time")

type Item struct{ DatasetID string `json:"dataset_id"`; Name string `json:"name"`; Subject string `json:"subject,omitempty"`; Session string `json:"session,omitempty"`; Run string `json:"run,omitempty"`; Status string `json:"status"`; Error string `json:"error,omitempty"`; Output json.RawMessage `json:"output,omitempty"` }
type Job struct{ ID string `json:"id"`; Name string `json:"name"`; Status string `json:"status"`; CreatedAt string `json:"created_at"`; UpdatedAt string `json:"updated_at"`; SaveOutput bool `json:"save_output"`; Parameters json.RawMessage `json:"parameters"`; Items []Item `json:"items"`; Summary map[string]int `json:"summary"`; Metrics map[string]any `json:"metrics,omitempty"` }
type Store struct{DB *sql.DB}
func(s *Store)Init(ctx context.Context)error{_,err:=s.DB.ExecContext(ctx,`CREATE TABLE IF NOT EXISTS batch_jobs(id TEXT PRIMARY KEY,created_at TEXT NOT NULL,state_json TEXT NOT NULL)`);if err!=nil{return err};rows,err:=s.DB.QueryContext(ctx,`SELECT state_json FROM batch_jobs`);if err!=nil{return err};interrupted:=[]Job{};for rows.Next(){var raw []byte;if err=rows.Scan(&raw);err!=nil{rows.Close();return err};var job Job;if json.Unmarshal(raw,&job)==nil&&job.Status=="running"{job.Status="interrupted";for i:=range job.Items{if job.Items[i].Status=="running"{job.Items[i].Status="interrupted"}};interrupted=append(interrupted,job)}};err=rows.Err();rows.Close();if err!=nil{return err};for i:=range interrupted{if err=s.Save(ctx,&interrupted[i]);err!=nil{return err}};return nil}
func(s *Store)Save(ctx context.Context,job *Job)error{job.UpdatedAt=time.Now().UTC().Format(time.RFC3339Nano);raw,err:=json.Marshal(job);if err!=nil{return err};_,err=s.DB.ExecContext(ctx,`INSERT INTO batch_jobs(id,created_at,state_json) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET state_json=excluded.state_json`,job.ID,job.CreatedAt,string(raw));return err}
func(s *Store)Get(ctx context.Context,id string)(*Job,error){var raw []byte;err:=s.DB.QueryRowContext(ctx,`SELECT state_json FROM batch_jobs WHERE id=?`,id).Scan(&raw);if errors.Is(err,sql.ErrNoRows){return nil,nil};if err!=nil{return nil,err};var job Job;err=json.Unmarshal(raw,&job);return &job,err}
func(s *Store)List(ctx context.Context)([]Job,error){rows,err:=s.DB.QueryContext(ctx,`SELECT state_json FROM batch_jobs ORDER BY created_at DESC`);if err!=nil{return nil,err};defer rows.Close();jobs:=[]Job{};for rows.Next(){var raw []byte;if err=rows.Scan(&raw);err!=nil{return nil,err};var job Job;if err=json.Unmarshal(raw,&job);err!=nil{return nil,err};jobs=append(jobs,job)};return jobs,rows.Err()}
func(s *Store)Delete(ctx context.Context,id string)error{_,err:=s.DB.ExecContext(ctx,`DELETE FROM batch_jobs WHERE id=? AND json_extract(state_json,'$.status') NOT IN ('running','pause_requested')`);return err}
